import type { Locale } from "../../i18n";
import type { VoicesText } from "../types";

// The voices that speak outside the Chronicle: the King's Words (BIBLE 12.4), his lines under
// the Regalia (11.5) and the Eclipse (13), what stays after a long absence (12.8), Célestine's
// crystal songs (10.3) and the Stallkeeper's sayings (10.4).
export const VOICES_TEXT: Record<Locale, VoicesText> = {
  en: {
    kingWords: [
      // 1: surprise
      "You're early.",
      // 2 to 5: recognition
      "Again, then.",
      "You hold the sword better tonight.",
      "I know that step. You favor the left foot.",
      "You. Good. I had hoped it would be you.",
      // 6 to 12: conversation
      "Mind the third step. It was loose in my father's time.",
      "The tapestry on the east wall was my mother's. Try not to bleed on it.",
      "There were apples in the courtyard, once. Small and sour. I miss the sour.",
      "Do the rats still take the grain? Good. Something should stay the same.",
      "Your hands are cold. This hall was never warm, not even in summer.",
      "If you see the smith, tell him I have not forgotten the hammer. He will know.",
      "I used to count the stars from that window. I stopped when they stopped moving.",
      // 13 to 20: confession
      "I sat down for a moment. Only a moment.",
      "The chair was not always this heavy. Or I was not.",
      "I asked for this night. I would ask again. I think I would.",
      "Someone was meant to walk ahead of me. I have forgiven him. Most nights.",
      "I walked that road before you. Every stone of it. Every night of it.",
      "The crown weighed less than a sword. That was the trouble with it.",
      "I told myself: one more night, and then I rest. Then I rested.",
      "I no longer remember my own face. I remember every crack in this throne.",
      // 21 to 30: warning
      "Don't give them everything. The stones never give it back.",
      "Keep one memory for yourself. A small one. Nobody will think to ask for it.",
      "If a chair ever looks comfortable, walk past it.",
      "The sky is thinner than it looks. Don't stare at the cracks.",
      "Never spend all of yourself. I have seen what walks out the other side.",
      "If a knight will not look at this throne, don't ask him why. Stand beside him.",
      "When a night feels short, be careful. Something is wearing thin.",
      "They call it the Morning. It is not what the word promises.",
      "Rest at dusk, if you must. Never here. Never in this hall.",
      "Whatever sits at the top of these stairs, don't let it be you.",
      // 31 to 40: pity and pride
      "You look tired. Good. It means you are still walking.",
      "You hit the way I used to. Harder, perhaps.",
      "Your company forgets you at every dusk. You come anyway. That is a king's work.",
      "I tried to count your nights. I lost count. I am proud of that.",
      "You're bleeding. Sit. No. Not here. Stand, then.",
      "Nobody told you it gets easier. It doesn't. You get stronger. That is all.",
      "My father would have liked you. He liked stubborn people. He raised one.",
      "Somewhere below, older than me, the night goes on. You'll see it. I never did.",
      "You carry this road well. Better than I did.",
      "Your hands shake a little now. Mine did too, near the end. Keep them on the hilt.",
      // 41 to 49: gratitude
      "Thank you for coming back. Nobody else does, you know.",
      "Thank you. For the rats, the roots, the dark. For the third step.",
      "The hall is quieter when you are gone. I did not used to mind.",
      "You carry all of them, and still you climb my stairs. Thank you.",
      "I hear the stones at dusk. Some were raised by walkers I knew. Thank you for keeping them.",
      "Each night you come, the glass holds a little longer. I feel it.",
      "I was not always glad to see you. I am now.",
      "You never asked me to get up. Thank you for that, too.",
      "Thank you. I mean it. I have not meant a word in a long time.",
      // 50: the request
      "Don't stop. I did."
    ],
    regaliaWords: [
      "That is my ring. Keep it. It knew my hand. It can learn yours.",
      "My mantle. The hem is still torn where the hounds caught it.",
      "You found my decree. Did you read it? I never did. I only sealed it.",
      "Look at you. Orvane, walking up my stairs.",
      "They fit you. That frightens me more than anything in the night.",
      "My ring, my mantle, my seal. Someone should wear them standing up.",
      "Majesty. There. Somebody had to say it to you first.",
      "I bow. Not low. My back is older than my kingdom.",
      "The court would have knelt. There is no court. I will do it.",
      "Take the road the way I took it. Only farther.",
      "You wear them better than I did. Don't let them wear you.",
      "If anyone asks who holds the night, tell them: you. Not the chair."
    ],
    eclipseWords: [
      "The third step. Mind it. Who told me that?",
      "My feet hurt. They have not hurt in years. Is it dusk already?",
      "I have a sword. Why do I have a sword? Oh. The road.",
      "The rats in the wheat. The roots. The bats. I know this road. I walked it.",
      "Wait. I was supposed to be climbing these stairs. Not sitting at the top.",
      "Who sits up there? He looks tired. Somebody should tell him to get up.",
      "One more night. I can do one more night. I can."
    ],
    dreams: [
      "There was a field, and the wheat was cut. You were not there when it happened.",
      "A river ran backward under a bridge, and you knew the name of every stone.",
      "A door stood open in a wall with no house behind it.",
      "Snow fell upward out of a well. Someone had left a bucket at the bottom.",
      "You walked a road with nothing on it. It was the longest road you ever walked.",
      "A bell rang in a village that had no tower.",
      "You were small, and a hand much bigger than yours held the sword with you.",
      "There was a table set for one. The chair was still warm.",
      "A horse grazed by the keep, saddled for someone who never came down.",
      "You counted the stars, and there was one too many.",
      "There was the sound of a sea, very close. Orvane never had a sea.",
      "Someone was humming in the next room. You never reached the door.",
      "Rain fell on the fields, and every drop was the same drop.",
      "You held a letter with your name on it. The rest of the page was empty.",
      "A light burned in a far window. You walked toward it all night. It stayed far.",
      "There was a garden where every flower had already been picked.",
      "The King was young, and laughing, and he did not see you.",
      "You lay in grass so tall the sky was only a thin blue strip.",
      "A candle burned down to nothing and did not go out.",
      "Your company sat by a fire, talking about a friend they could not name. They had kept a seat.",
      "Wind came through a crack in the sky, and it smelled of bread.",
      "A staircase went down forever, and you were not afraid of it.",
      "The moon stopped, looked at you for a while, and went on.",
      "Something warm was set down beside you. By the time you turned, it was cold."
    ],
    songs: [
      "hmmm. hmm. this one is warm.",
      "la la, loo. it hums in blue.",
      "shh. listen. it's humming the shape of you.",
      "ting. ting. it landed right where you were standing.",
      "oh, this one was waiting. for you, i think.",
      "mmm-mmm. round and bright and a little bit sad.",
      "it rings like a spoon on a cup. do you hear?",
      "hoo. hoo. the sky dropped a note.",
      "this one sings high, high, higher. there.",
      "bright bright bright. oh. gone. it's inside you now.",
      "ah. it tastes like the very first night.",
      "la. la. la. it knows the tune. who taught it?",
      "the whole sky is leaning in tonight. can you feel it lean?",
      "tink. a little star that fell slowly.",
      "it hummed before it came. did you hear it before it came?",
      "mm. it's warm on one side. the side that faced you.",
      "listen, there's a lullaby in it. no. it stopped.",
      "dee dee dum. it likes you. they all like you.",
      "shh. it's still humming. from very far away.",
      "oh. this one sounds like a window. i don't know why.",
      "it's ringing, ringing. catch it before it forgets.",
      "hmm-hm-hm. i sing it back, and it sings it back.",
      "so quiet. a whisper with a light in it.",
      "ooh. it went all silver when you turned.",
      "one note. only one. it's enough.",
      "they sing louder when you're here. i noticed.",
      "bum, bum. like a heart. whose, though?",
      "la-li-lo. the light is humming. hum with it.",
      "cold and bright and singing, and now it's yours.",
      "hush. hush. somebody is near. it's nice."
    ],
    sayings: [
      "Everything is for sale. Nothing is for keeps.",
      "Shards, please. The sky will not mend itself, and I do not mend it for free.",
      "Welcome back. You were expected. Everyone is.",
      "Prices hold. It is the only thing in this night that does.",
      "I do not haggle. The night is long enough already.",
      "A shard for a chest. A chest for a hope. That is a fair trade.",
      "Bottled time is not refundable. Time rarely is.",
      "I have sold to kings. They paid the same as you.",
      "Take your time. Nothing here is going anywhere. Neither are we.",
      "Every shard you bring me goes back into the sky. Look up, some night.",
      "You look like you are running low. Most people are.",
      "Come again. You will. Everyone does."
    ]
  },
  fr: {
    kingWords: [
      // 1 : surprise
      "Tu es en avance.",
      // 2 à 5 : reconnaissance
      "Encore, donc.",
      "Tu tiens mieux ton épée, ce soir.",
      "Je connais ce pas. Tu ménages ta jambe gauche.",
      "Toi. Tant mieux. J'espérais que ce serait toi.",
      // 6 à 12 : conversation
      "Attention à la troisième marche. Elle branlait déjà du temps de mon père.",
      "La tapisserie du mur est, c'était celle de ma mère. Évite de saigner dessus.",
      "Il y avait des pommes dans la cour, autrefois. Petites, acides. L'acide me manque.",
      "Les rats volent encore le grain ? Bien. Il faut que quelque chose reste pareil.",
      "Tu as les mains froides. Cette salle n'a jamais été chaude, même en été.",
      "Si tu croises le forgeron, dis-lui que je n'ai pas oublié le marteau. Il comprendra.",
      "Je comptais les étoiles depuis cette fenêtre. J'ai arrêté quand elles ont cessé de bouger.",
      // 13 à 20 : confession
      "Je me suis assis un instant. Rien qu'un instant.",
      "Ce siège n'a pas toujours été si lourd. Ou c'est moi qui ne l'étais pas.",
      "J'ai demandé cette nuit. Je la redemanderais. Je crois.",
      "Quelqu'un devait marcher devant moi. Je lui ai pardonné. Presque toutes les nuits.",
      "J'ai marché cette route avant toi. Chaque pierre. Chaque nuit.",
      "La couronne pesait moins qu'une épée. C'était bien ça, le problème.",
      "Je me suis dit : encore une nuit, et je me repose. Et je me suis reposé.",
      "Je ne me souviens plus de mon visage. Je me souviens de chaque fêlure de ce trône.",
      // 21 à 30 : avertissement
      "Ne leur donne pas tout. Les pierres ne rendent jamais rien.",
      "Garde un souvenir pour toi. Un petit. Personne ne pensera à te le demander.",
      "Si un siège te semble confortable, passe ton chemin.",
      "Le ciel est plus mince qu'il n'en a l'air. Ne fixe pas les fêlures.",
      "Ne te dépense jamais tout entier. J'ai vu ce qui ressort de l'autre côté.",
      "Si un chevalier refuse de regarder ce trône, ne lui demande pas pourquoi. Tiens-toi près de lui.",
      "Quand une nuit te paraît courte, méfie-toi. Quelque chose s'use.",
      "Ils l'appellent le Matin. Il ne tient pas ce que le mot promet.",
      "Repose-toi au crépuscule, s'il le faut. Jamais ici. Jamais dans cette salle.",
      "Quoi qu'il y ait en haut de ces marches, fais que ce ne soit pas toi.",
      // 31 à 40 : pitié et fierté
      "Tu as l'air fatigué. Tant mieux. Ça veut dire que tu marches encore.",
      "Tu frappes comme je frappais. Plus fort, peut-être.",
      "Ta compagnie t'oublie à chaque crépuscule. Tu reviens quand même. C'est un travail de roi.",
      "J'ai voulu compter tes nuits. J'ai perdu le compte. J'en suis fier.",
      "Tu saignes. Assieds-toi. Non. Pas ici. Reste debout, alors.",
      "Personne ne t'a dit que ça devenait plus facile. Ça ne le devient pas. C'est toi qui deviens plus fort.",
      "Mon père t'aurait aimé. Il aimait les têtus. Il en a élevé un.",
      "Plus bas, plus vieille que moi, la nuit continue. Tu la verras. Moi jamais.",
      "Tu portes bien cette route. Mieux que moi.",
      "Tes mains tremblent un peu, maintenant. Les miennes aussi, vers la fin. Ne lâche pas la poignée.",
      // 41 à 49 : gratitude
      "Merci de revenir. Personne d'autre ne le fait, tu sais.",
      "Merci. Pour les rats, les racines, le noir. Pour la troisième marche.",
      "La salle est plus calme quand tu n'es pas là. Avant, ça m'était égal.",
      "Tu les portes tous, et tu montes encore mes marches. Merci.",
      "J'entends les pierres, au crépuscule. Certaines, ce sont des marcheurs que j'ai connus. Merci de les garder.",
      "Chaque nuit où tu viens, la voûte tient un peu plus. Je le sens.",
      "Je n'ai pas toujours été content de te voir. Maintenant, si.",
      "Tu ne m'as jamais demandé de me lever. Merci pour ça aussi.",
      "Merci. Je le pense. Il y a longtemps que je n'ai rien pensé de ce que je dis.",
      // 50 : la demande
      "Ne t'arrête pas. Moi, je l'ai fait."
    ],
    regaliaWords: [
      "C'est ma bague. Garde-la. Elle a connu ma main. Elle apprendra la tienne.",
      "Mon manteau. L'ourlet est encore déchiré là où les chiens l'ont pris.",
      "Tu as trouvé mon décret. Tu l'as lu ? Moi jamais. Je l'ai seulement scellé.",
      "Regarde-toi. Orvane qui monte mes marches.",
      "Ils te vont. Ça m'effraie plus que tout ce que la nuit contient.",
      "Ma bague, mon manteau, mon sceau. Quelqu'un devrait les porter debout.",
      "Majesté. Voilà. Il fallait bien que quelqu'un te le dise en premier.",
      "Je m'incline. Pas bien bas. Mon dos est plus vieux que mon royaume.",
      "La cour se serait agenouillée. Il n'y a plus de cour. Je le ferai.",
      "Prends la route comme je l'ai prise. Seulement, va plus loin.",
      "Tu les portes mieux que moi. Ne les laisse pas te porter.",
      "Si on te demande qui tient la nuit, réponds : toi. Pas le siège."
    ],
    eclipseWords: [
      "La troisième marche. Attention. Qui m'a dit ça ?",
      "J'ai mal aux pieds. Ça fait des années. C'est déjà le crépuscule ?",
      "J'ai une épée. Pourquoi j'ai une épée ? Ah. La route.",
      "Les rats dans le blé. Les racines. Les chauves-souris. Je connais cette route. Je l'ai marchée.",
      "Attends. Je devais monter ces marches. Pas m'asseoir en haut.",
      "Qui est assis là-haut ? Il a l'air fatigué. Quelqu'un devrait lui dire de se lever.",
      "Encore une nuit. Je peux encore une nuit. Je peux."
    ],
    dreams: [
      "Il y avait un champ, et le blé était coupé. Tu n'étais pas là quand c'est arrivé.",
      "Une rivière coulait à rebours sous un pont, et tu savais le nom de chaque pierre.",
      "Une porte ouverte dans un mur, et pas de maison derrière.",
      "La neige montait d'un puits. Quelqu'un avait laissé un seau au fond.",
      "Tu marchais sur une route où il n'y avait rien. La plus longue que tu aies jamais marchée.",
      "Une cloche sonnait dans un village sans clocher.",
      "Tu étais petit, et une main bien plus grande que la tienne tenait l'épée avec toi.",
      "Une table mise pour un seul. La chaise était encore tiède.",
      "Un cheval broutait au pied du donjon, sellé pour quelqu'un qui n'est jamais descendu.",
      "Tu comptais les étoiles, et il y en avait une de trop.",
      "On entendait la mer, toute proche. Orvane n'a jamais eu de mer.",
      "Quelqu'un fredonnait dans la pièce d'à côté. Tu n'as jamais atteint la porte.",
      "Il pleuvait sur les Plaines, et chaque goutte était la même goutte.",
      "Tu tenais une lettre à ton nom. Le reste de la page était vide.",
      "Une lumière brûlait à une fenêtre lointaine. Tu as marché vers elle toute la nuit. Elle est restée loin.",
      "Il y avait un jardin où toutes les fleurs avaient déjà été cueillies.",
      "Le roi était jeune, il riait, et il ne te voyait pas.",
      "Tu étais couché dans une herbe si haute que le ciel n'était plus qu'un fil bleu.",
      "Une bougie a brûlé jusqu'au bout et ne s'est pas éteinte.",
      "Ta compagnie parlait, autour d'un feu, d'un ami dont personne ne retrouvait le nom. Ils avaient gardé une place.",
      "Le vent passait par une fêlure du ciel, et il sentait le pain.",
      "Un escalier descendait sans fin, et tu n'avais pas peur.",
      "La lune s'est arrêtée, t'a regardé un moment, puis elle est repartie.",
      "On a posé quelque chose de chaud près de toi. Le temps de te retourner, c'était froid."
    ],
    songs: [
      "hmmm. hmm. celui-là est tout chaud.",
      "la la, lou. il chante en bleu.",
      "chut. écoute. il fredonne ta forme.",
      "ting. ting. il est tombé juste là où tu étais.",
      "oh, celui-là attendait. toi, je crois.",
      "mmm-mmm. rond et clair et un peu triste.",
      "il tinte comme une cuillère sur un bol. tu entends ?",
      "hou. hou. le ciel a laissé tomber une note.",
      "celui-là chante haut, haut, plus haut. voilà.",
      "clair clair clair. oh. parti. il est en toi maintenant.",
      "ah. il a le goût de la toute première nuit.",
      "la. la. la. il connaît l'air. qui le lui a appris ?",
      "tout le ciel se penche, ce soir. tu le sens pencher ?",
      "tink. une petite étoile, tombée lentement.",
      "il fredonnait avant d'arriver. tu l'as entendu avant, toi ?",
      "mm. il est chaud d'un côté. le côté tourné vers toi.",
      "écoute, il y a une berceuse dedans. non. elle s'est tue.",
      "di di doum. il t'aime bien. ils t'aiment tous bien.",
      "chut. il fredonne encore. de très, très loin.",
      "oh. celui-là sonne comme une fenêtre. je ne sais pas pourquoi.",
      "il sonne, il sonne. attrape-le avant qu'il oublie.",
      "hmm-hm-hm. je lui chante l'air, il me le rechante.",
      "tout doux. un murmure avec une lumière dedans.",
      "ooh. il est devenu tout argent quand tu t'es tourné.",
      "une note. une seule. ça suffit.",
      "ils chantent plus fort quand tu es là. j'ai remarqué.",
      "boum, boum. comme un cœur. le cœur de qui ?",
      "la-li-lo. la lumière fredonne. fredonne avec elle.",
      "froid et clair et qui chante, et maintenant il est à toi.",
      "chut. chut. quelqu'un est tout près. c'est doux."
    ],
    sayings: [
      "Tout est à vendre. Rien n'est à garder.",
      "Des éclats, s'il te plaît. Le ciel ne se recoud pas tout seul, et je ne le recouds pas gratis.",
      "Bon retour. On t'attendait. On attend tout le monde.",
      "Les prix tiennent. C'est bien la seule chose qui tienne, cette nuit.",
      "Je ne marchande pas. La nuit est assez longue comme ça.",
      "Un éclat pour un coffre. Un coffre pour un espoir. C'est un prix honnête.",
      "Le temps en bouteille n'est ni repris ni échangé. Le temps l'est rarement.",
      "J'ai vendu à des rois. Ils ont payé le même prix que toi.",
      "Prends ton temps. Rien ici ne s'en va. Nous non plus.",
      "Chaque éclat que tu m'apportes retourne au ciel. Lève les yeux, une nuit.",
      "Tu as l'air à court. Comme presque tout le monde.",
      "Reviens. Tu reviendras. Tout le monde revient."
    ]
  }
};
