import type { Locale } from "../../i18n";
import type { VoicesText } from "../types";

// The voices that speak outside the Chronicle: the King's Words (BIBLE 12.4), his lines under
// the Regalia (11.5) and the Eclipse (13), what stays after a long absence (12.8), Célestine's
// crystal songs (10.3) and the Stallkeeper's sayings (10.4).
export const VOICES_TEXT: Record<Locale, VoicesText> = {
  en: {
    kingWords: [
      // 1: surprise
      "You're early.",
      // 2 to 5: recognition
      "Again, then. You climb, I fall, and the night starts over.",
      "You hold the sword better tonight. The nights are teaching you.",
      "I know that step. You favor the left foot. I have watched you climb these stairs before.",
      "You. Good. I had hoped it would be you again.",
      // 6 to 12: conversation
      "Mind the third step. It was loose in my father's time.",
      "The tapestry on the east wall was my mother's. Try not to bleed on it.",
      "There were apples in the courtyard, before the night. Small and sour. I miss the sour.",
      "Do the rats still take the grain? Good. Something in my kingdom should stay the same.",
      "Your hands are cold. This hall was never warm, not even in summer. There has been no summer in a long time.",
      "If you see Brom the smith, tell him I have not forgotten the hammer I asked him for. He will know.",
      "I used to count the stars from that window. They have not moved since this night began.",
      // 13 to 20: confession
      "I walked this road before you, night after night. Then I sat down for a moment. Only a moment.",
      "The crown holds whoever stops walking. I stopped, and it held me. That is what I am.",
      "I asked Eldra to weave this night, to keep the Morning out of Orvane. I would ask again. I think I would.",
      "My knight was meant to walk the first night. He ran. I walked in his place. I have forgiven him. Most nights.",
      "I cleared the Remnants myself, those first nights, so they would not pile up and tear the night apart.",
      "The crown weighed less than a sword. That was the trouble with it. It let me stop.",
      "I told myself: one more night, and then I rest. Then I rested.",
      "I no longer remember my own face. I remember every crack in this throne. That is what sitting costs.",
      // 21 to 30: warning
      "Don't give the altars everything. The stones keep your memories and never give them back.",
      "Keep one memory for yourself. A small one. Nobody will think to ask for it.",
      "If a chair ever looks comfortable, walk past it. That is how I became this.",
      "The Sky-Glass is cracked. Your shards are pieces of it. If it breaks, the Morning comes in.",
      "Never spend all your memories. I have seen walkers who did. They still walk, with nothing left inside.",
      "If my old knight will not look at this throne, don't ask him why. Stand beside him.",
      "When a night feels short, be careful. The weave is wearing thin.",
      "They call it the Morning. It is not a sunrise. It is the end of everything that remembers.",
      "Rest at dusk, if you must. Never here. Never in this hall.",
      "Any walker who stops for good at the top of these stairs becomes what I am. Don't let it be you.",
      // 31 to 40: pity and pride
      "You look tired. Good. It means you are still walking.",
      "You hit the way I used to. Harder, perhaps.",
      "Your company forgets you at every dusk. You come anyway. That is a king's work.",
      "I tried to count your nights. I lost count. I am proud of that.",
      "You're bleeding. Sit. No. Not here. Stand, then.",
      "Nobody told you it gets easier. It doesn't. You get stronger. That is all.",
      "My father would have liked you. He liked stubborn people. He raised one.",
      "Below this road the night goes deeper, older than me. You'll see it. I never did.",
      "You carry this road well. Better than I did.",
      "Your hands shake a little now. Mine did too, near the end. Keep them on the hilt.",
      // 41 to 49: gratitude
      "Thank you for coming back. Nobody else does, you know.",
      "Thank you. For the rats, the roots, the dark. For the third step.",
      "The hall is quieter when you are gone. I did not used to mind.",
      "You carry all of them, and still you climb my stairs. Thank you.",
      "I hear the altars at dusk. Walkers I knew raised some of them. Thank you for keeping them.",
      "Each night you come, the Sky-Glass holds a little longer. I feel it.",
      "I was not always glad to see you. I am now.",
      "You never asked me to get up. Thank you for that, too.",
      "Thank you. I mean it. I have not meant a word in a long time.",
      // 50: the request
      "Don't stop. I did."
    ],
    regaliaWords: [
      "That is my ring. Keep it. It knew my hand. It can learn yours.",
      "My mantle. The hem is still torn where the hounds caught it, the last day before the night.",
      "You found my decree, the one that asked for this night. Did you read it? I never did. I only sealed it.",
      "Look at you, in my ring and my mantle. Orvane's king, climbing up to Orvane's king.",
      "They fit you. That frightens me. They fit me too, before I sat down.",
      "My ring, my mantle, my seal. Someone should wear them standing up.",
      "Majesty. There. Somebody had to say it to you first.",
      "I bow. Not low. My back is older than my kingdom.",
      "The court would have knelt. There is no court. I will do it.",
      "Take the road the way I took it. Only farther.",
      "You wear them better than I did. Don't let them wear you.",
      "If anyone asks who holds the night, tell them: you. Not the chair."
    ],
    kingRepels: ["Come back when your hands stop shaking."],
    eclipseWords: [
      "The third step. Mind it. Who told me that? I have not climbed a stair in so long.",
      "My feet hurt. They have not hurt since I last walked the road. Is it dusk already?",
      "I have a sword. Why do I have a sword? Oh. The road. I used to walk it, like you.",
      "The rats in the wheat. The roots. The bats. I know this road. I walked it first.",
      "Wait. I was supposed to be climbing these stairs. Not sitting at the top.",
      "Who sits up there? He looks tired. Somebody should tell him to get up. Oh. It's me.",
      "One more night. I can do one more night. I can."
    ],
    dreams: [
      "In your sleep, the Plains lay in daylight, the wheat cut and stacked. Nobody in Orvane has seen daylight since the night began.",
      "In your sleep, a stream in the forest ran backward, and you knew every stone in it. You have walked past them that many times.",
      "In your sleep, a door stood in a wall with no house behind it. The night remembers the door. It forgot the rest.",
      "You slept, and the company walked on without you. Far off, you could hear them still fighting on the road.",
      "In your sleep you walked a road with no Remnants and no company. It was the longest road you ever walked.",
      "In your sleep, a bell rang in a village of the Plains. It was the last bell rung before the night began.",
      "In your sleep you were small, and the Sword-Mother's hand held the sword with you. She taught walkers long before you.",
      "In your sleep, a table was laid for one in the keep, the spoon on the left, where you reach. The King had laid it.",
      "In your sleep, a horse grazed by the keep, saddled for a king who never came down from his throne.",
      "In your sleep you counted the stars through the Sky-Glass. They were where they were last night, and every night before.",
      "In your sleep you heard a sea, very close. Orvane never had a sea. Something older than the kingdom did.",
      "In your sleep, someone in the next room hummed the tune Célestine sings to the crystals. You never reached the door.",
      "In your sleep, rain fell on the Plains, and every drop was the same drop, falling again. Like the night.",
      "In your sleep you held a letter addressed to Aldric. The rest of the page was empty. Nobody remembered what to write.",
      "In your sleep, Maëlle carved a notch in her fence post, then counted them all. She stopped at a number she did not like.",
      "In your sleep, the keep's courtyard had apples again, small and sour. The King was eating one.",
      "In your sleep, the King was young and laughing, before the night, before the crown. He did not see you.",
      "In your sleep you lay in tall grass and nothing hunted you. You had forgotten what that felt like.",
      "In your sleep, Brother Cinder's flame burned down to nothing and did not go out. He smiled, as if he had expected it.",
      "In your sleep, your company sat by a fire, talking about a friend none of them could name. They had kept a seat anyway.",
      "In your sleep, wind came through a crack in the Sky-Glass. It smelled of bread, and of morning.",
      "In your sleep, a staircase went down below the keep, forever, and you were not afraid of it.",
      "In your sleep, Pip the golden rat sat on a heap of coin, counting it. He counted it twice, then looked at you.",
      "In your sleep, someone set a cup of tea down beside you and went back to the road. By the time you woke, it was cold."
    ],
    songs: [
      "hmmm. hmm. this one is warm.",
      "la la, loo. it hums in blue.",
      "shh. listen. it's humming the shape of you.",
      "ting. ting. it landed right where you were standing.",
      "oh, this one was waiting. for you, i think.",
      "mmm-mmm. round and bright and a little bit sad.",
      "it rings like a spoon on a cup. do you hear?",
      "hoo. hoo. the sky dropped a note.",
      "this one sings high, high, higher. there.",
      "bright bright bright. oh. gone. it's inside you now.",
      "ah. it tastes like the very first night.",
      "la. la. la. it knows the tune. who taught it?",
      "the whole sky is leaning in tonight. can you feel it lean?",
      "tink. a little piece of sky that fell slowly.",
      "it hummed before it came. did you hear it before it came?",
      "mm. it's warm on one side. the side that faced you.",
      "listen, there's a lullaby in it. no. it stopped.",
      "dee dee dum. it likes you. they all like you.",
      "shh. it's still humming. from very far away.",
      "oh. this one fell from the crack above the keep. it's still warm.",
      "it's ringing, ringing. catch it before it forgets.",
      "hmm-hm-hm. i sing it back, and it sings it back.",
      "so quiet. a whisper with a light in it.",
      "ooh. it went all silver when you turned.",
      "one note. only one. it's enough.",
      "they sing louder when you're here. i noticed.",
      "bum, bum. like a heart. whose, though?",
      "la-li-lo. the light is humming. hum with it.",
      "cold and bright and singing, and now it's yours.",
      "hush. hush. somebody is looking at us. it's nice."
    ],
    sayings: [
      "Everything is for sale. Nothing is for keeps.",
      "Shards, please. The sky will not mend itself, and I do not mend it for free.",
      "Welcome back. You were expected. Everyone is.",
      "Prices hold. It is the only thing in this night that does.",
      "I do not haggle. The night is long enough already.",
      "A shard for a chest. A chest for a hope. That is a fair trade.",
      "Bottled time is not refundable. Time rarely is.",
      "I have sold to kings. They paid the same as you.",
      "Take your time. Nothing here is going anywhere. Neither are we.",
      "Every shard you bring me goes back into the sky. Look up, some night.",
      "You look like you are running low. Most people are.",
      "Come again. You will. Everyone does."
    ]
  },
  fr: {
    kingWords: [
      // 1 : surprise
      "Tu es en avance.",
      // 2 à 5 : reconnaissance
      "Encore, donc. Tu montes, je tombe, et la nuit recommence.",
      "Tu tiens mieux ton épée, ce soir. Les nuits t'apprennent.",
      "Je connais ce pas. Tu ménages ta jambe gauche. Je t'ai déjà vu monter ces marches.",
      "Toi. Tant mieux. J'espérais que ce serait encore toi.",
      // 6 à 12 : conversation
      "Attention à la troisième marche. Elle branlait déjà du temps de mon père.",
      "La tapisserie du mur est, c'était celle de ma mère. Évite de saigner dessus.",
      "Il y avait des pommes dans la cour, avant la nuit. Petites, acides. L'acide me manque.",
      "Les rats volent encore le grain ? Bien. Il faut que quelque chose reste pareil, dans mon royaume.",
      "Tu as les mains froides. Cette salle n'a jamais été chaude, même en été. Il n'y a plus d'été depuis longtemps.",
      "Si tu croises Brom le forgeron, dis-lui que je n'ai pas oublié le marteau que je lui ai demandé. Il comprendra.",
      "Je comptais les étoiles depuis cette fenêtre. Elles n'ont plus bougé depuis que cette nuit a commencé.",
      // 13 à 20 : confession
      "J'ai parcouru cette route avant toi, nuit après nuit. Puis je me suis assis un instant. Rien qu'un instant.",
      "La couronne garde celui qui cesse de marcher. J'ai cessé, et elle m'a gardé. Voilà ce que je suis.",
      "J'ai demandé à Eldra de tisser cette nuit, pour garder le Matin hors d'Orvane. Je le redemanderais. Je crois.",
      "Mon chevalier devait marcher la première nuit. Il a fui. J'ai marché à sa place. Je lui ai pardonné. Presque toutes les nuits.",
      "Ces premières nuits, j'ai abattu les Vestiges moi-même, pour qu'ils ne s'entassent pas jusqu'à déchirer la nuit.",
      "La couronne pesait moins qu'une épée. C'était bien ça, le problème. Elle m'a laissé m'arrêter.",
      "Je me suis dit : encore une nuit, et je me repose. Et je me suis reposé.",
      "Je ne me souviens plus de mon visage. Je me souviens de chaque fêlure de ce trône. Voilà ce que ça coûte, de s'asseoir.",
      // 21 à 30 : avertissement
      "Ne donne pas tout aux autels. Les pierres gardent tes souvenirs et ne les rendent jamais.",
      "Garde un souvenir pour toi. Un petit. Personne ne pensera à te le demander.",
      "Si un siège te semble confortable, passe ton chemin. C'est comme ça que je suis devenu ceci.",
      "La Voûte de verre est fêlée. Tes éclats en sont des morceaux. Si elle se brise, le Matin entre.",
      "Ne dépense jamais tous tes souvenirs. J'ai vu des marcheurs le faire. Ils marchent encore, vides.",
      "Si mon ancien chevalier refuse de regarder ce trône, ne lui demande pas pourquoi. Tiens-toi près de lui.",
      "Quand une nuit te paraît courte, méfie-toi. Le tissage s'use.",
      "Ils l'appellent le Matin. Ce n'est pas un lever de soleil. C'est la fin de tout ce qui se souvient.",
      "Repose-toi au crépuscule, s'il le faut. Jamais ici. Jamais dans cette salle.",
      "Le marcheur qui s'arrête pour de bon en haut de ces marches devient ce que je suis. Fais que ce ne soit pas toi.",
      // 31 à 40 : pitié et fierté
      "Tu as l'air fatigué. Tant mieux. Ça veut dire que tu marches encore.",
      "Tu frappes comme je frappais. Plus fort, peut-être.",
      "Ta compagnie t'oublie à chaque crépuscule. Tu reviens quand même. C'est un travail de roi.",
      "J'ai voulu compter tes nuits. J'ai perdu le compte. J'en suis fier.",
      "Tu saignes. Assieds-toi. Non. Pas ici. Reste debout, alors.",
      "Personne ne t'a dit que ça devenait plus facile. Ça ne le devient pas. C'est toi qui deviens plus fort.",
      "Mon père t'aurait aimé. Il aimait les têtus. Il en a élevé un.",
      "Sous cette route, la nuit descend encore, plus vieille que moi. Tu la verras. Moi jamais.",
      "Tu portes bien cette route. Mieux que moi.",
      "Tes mains tremblent un peu, maintenant. Les miennes aussi, vers la fin. Ne lâche pas la poignée.",
      // 41 à 49 : gratitude
      "Merci de revenir. Personne d'autre ne le fait, tu sais.",
      "Merci. Pour les rats, les racines, le noir. Pour la troisième marche.",
      "La salle est plus calme quand tu n'es pas là. Avant, ça m'était égal.",
      "Tu les portes tous, et tu montes encore mes marches. Merci.",
      "J'entends les autels, au crépuscule. Des marcheurs que j'ai connus en ont dressé certains. Merci de les garder.",
      "Chaque nuit où tu viens, la Voûte de verre tient un peu plus. Je le sens.",
      "Je n'ai pas toujours été content de te voir. Maintenant, si.",
      "Tu ne m'as jamais demandé de me lever. Merci pour ça aussi.",
      "Merci. Je le pense. Ça faisait longtemps que je ne pensais plus ce que je disais.",
      // 50 : la demande
      "Ne t'arrête pas. Moi, je l'ai fait."
    ],
    regaliaWords: [
      "C'est ma bague. Garde-la. Elle a connu ma main. Elle apprendra la tienne.",
      "Mon manteau. L'ourlet est encore déchiré là où les chiens l'ont pris, le dernier jour avant la nuit.",
      "Tu as trouvé mon décret, celui qui demandait cette nuit. Tu l'as lu ? Moi jamais. Je l'ai seulement scellé.",
      "Regarde-toi, avec ma bague et mon manteau. Le roi d'Orvane qui monte vers le roi d'Orvane.",
      "Ils te vont. Ça m'effraie. Ils m'allaient aussi, avant que je m'assoie.",
      "Ma bague, mon manteau, mon sceau. Quelqu'un devrait les porter debout.",
      "Majesté. Voilà. Il fallait bien que quelqu'un te le dise en premier.",
      "Je m'incline. Pas bien bas. Mon dos est plus vieux que mon royaume.",
      "La cour se serait agenouillée. Il n'y a plus de cour. Je le ferai.",
      "Prends la route comme je l'ai prise. Seulement, va plus loin.",
      "Tu les portes mieux que moi. Ne les laisse pas te porter.",
      "Si on te demande qui tient la nuit, réponds : toi. Pas le siège."
    ],
    kingRepels: ["Reviens quand tes mains ne trembleront plus."],
    eclipseWords: [
      "La troisième marche. Attention. Qui m'a dit ça ? Ça fait si longtemps que je n'ai pas monté d'escalier.",
      "J'ai mal aux pieds. Ça ne m'était plus arrivé depuis la dernière fois que j'ai marché sur la route. C'est déjà le crépuscule ?",
      "J'ai une épée. Pourquoi j'ai une épée ? Ah. La route. Je la parcourais, comme toi.",
      "Les rats dans le blé. Les racines. Les chauves-souris. Je connais cette route. Je l'ai parcourue le premier.",
      "Attends. Je devais monter ces marches. Pas m'asseoir en haut.",
      "Qui est assis là-haut ? Il a l'air fatigué. Quelqu'un devrait lui dire de se lever. Ah. C'est moi.",
      "Encore une nuit. Je peux encore une nuit. Je peux."
    ],
    dreams: [
      "Dans ton sommeil, les Plaines étaient en plein jour, le blé en meules. Personne en Orvane n'a vu le jour depuis que la nuit a commencé.",
      "Dans ton sommeil, un ruisseau de la forêt coulait à rebours, et tu connaissais chaque pierre. Tu es passé devant tant de fois.",
      "Dans ton sommeil, une porte dans un mur, sans maison derrière. La nuit se souvient de la porte. Elle a oublié le reste.",
      "Tu dormais, et la compagnie a continué sans toi. Au loin, tu les entendais encore se battre sur la route.",
      "Dans ton sommeil, tu marchais sur une route sans Vestiges et sans compagnie. La plus longue que tu aies jamais parcourue.",
      "Dans ton sommeil, une cloche sonnait dans un village des Plaines. La dernière cloche sonnée avant que la nuit tombe.",
      "Dans ton sommeil, tu étais petit, et la main de la Mère-des-Épées tenait l'épée avec toi. Elle formait des marcheurs bien avant toi.",
      "Dans ton sommeil, une table mise pour un seul au donjon, la cuillère à gauche, là où ta main la cherche. C'est le Roi qui l'avait mise.",
      "Dans ton sommeil, un cheval broutait au pied du donjon, sellé pour un roi qui n'est jamais descendu de son trône.",
      "Dans ton sommeil, tu comptais les étoiles à travers la Voûte. Elles étaient à la même place que la nuit d'avant, et toutes les autres.",
      "Dans ton sommeil, tu entendais la mer, toute proche. Orvane n'a jamais eu de mer. Quelque chose de plus vieux que le royaume, si.",
      "Dans ton sommeil, quelqu'un fredonnait dans la pièce d'à côté l'air que Célestine chante aux cristaux. Tu n'as jamais atteint la porte.",
      "Dans ton sommeil, il pleuvait sur les Plaines, et chaque goutte était la même, qui retombait. Comme la nuit.",
      "Dans ton sommeil, tu tenais une lettre adressée à Aldric. Le reste de la page était vide. Personne ne savait plus quoi écrire.",
      "Dans ton sommeil, Maëlle taillait une encoche dans son poteau, puis les comptait toutes. Elle s'arrêtait à un nombre qui lui déplaisait.",
      "Dans ton sommeil, il y avait de nouveau des pommes dans la cour du donjon, petites, acides. Le Roi en mangeait une.",
      "Dans ton sommeil, le Roi était jeune et riait, avant la nuit, avant la couronne. Il ne te voyait pas.",
      "Dans ton sommeil, tu étais couché dans l'herbe haute et rien ne te chassait. Tu avais oublié ce que ça faisait.",
      "Dans ton sommeil, la flamme de Frère Cendre a brûlé jusqu'au bout sans s'éteindre. Il a souri, comme s'il s'y attendait.",
      "Dans ton sommeil, ta compagnie parlait, autour d'un feu, d'un ami dont personne ne retrouvait le nom. Ils lui avaient gardé une place.",
      "Dans ton sommeil, le vent passait par une fêlure de la Voûte. Il sentait le pain, et le matin.",
      "Dans ton sommeil, un escalier descendait sous le donjon, sans fin, et tu n'avais pas peur.",
      "Dans ton sommeil, Pip le rat doré comptait un tas de pièces. Il l'a compté deux fois, puis il t'a regardé.",
      "Dans ton sommeil, quelqu'un a posé une tasse de thé près de toi avant de repartir sur la route. À ton réveil, elle était froide."
    ],
    songs: [
      "hmmm. hmm. celui-là est tout chaud.",
      "la la, lou. il chante en bleu.",
      "chut. écoute. il fredonne ta forme.",
      "ting. ting. il est tombé juste là où tu étais.",
      "oh, celui-là attendait. toi, je crois.",
      "mmm-mmm. rond et clair et un peu triste.",
      "il tinte comme une cuillère sur un bol. tu entends ?",
      "hou. hou. le ciel a laissé tomber une note.",
      "celui-là chante haut, haut, plus haut. voilà.",
      "clair clair clair. oh. parti. il est en toi maintenant.",
      "ah. il a le goût de la toute première nuit.",
      "la. la. la. il connaît l'air. qui le lui a appris ?",
      "tout le ciel se penche, ce soir. tu le sens pencher ?",
      "tink. un petit bout de ciel, tombé lentement.",
      "il fredonnait avant d'arriver. tu l'as entendu avant, toi ?",
      "mm. il est chaud d'un côté. le côté tourné vers toi.",
      "écoute, il y a une berceuse dedans. non. elle s'est tue.",
      "di di doum. il t'aime bien. ils t'aiment tous bien.",
      "chut. il fredonne encore. de très, très loin.",
      "oh. celui-là est tombé de la fêlure au-dessus du donjon. il est encore chaud.",
      "il sonne, il sonne. attrape-le avant qu'il oublie.",
      "hmm-hm-hm. je lui chante l'air, il me le rechante.",
      "tout doux. un murmure avec une lumière dedans.",
      "ooh. il est devenu tout argent quand tu t'es tourné.",
      "une note. une seule. ça suffit.",
      "ils chantent plus fort quand tu es là. j'ai remarqué.",
      "boum, boum. comme un cœur. le cœur de qui ?",
      "la-li-lo. la lumière fredonne. fredonne avec elle.",
      "froid et clair et qui chante, et maintenant il est à toi.",
      "chut. chut. quelqu'un nous regarde. c'est doux."
    ],
    sayings: [
      "Tout est à vendre. Rien n'est à garder.",
      "Des éclats, s'il te plaît. Le ciel ne se recoud pas tout seul, et je ne le recouds pas gratis.",
      "Bon retour. On t'attendait. On attend tout le monde.",
      "Les prix tiennent. C'est bien la seule chose qui tienne, cette nuit.",
      "Je ne marchande pas. La nuit est assez longue comme ça.",
      "Un éclat pour un coffre. Un coffre pour un espoir. C'est un prix honnête.",
      "Le temps en bouteille n'est ni repris ni échangé. Le temps l'est rarement.",
      "J'ai vendu à des rois. Ils ont payé le même prix que toi.",
      "Prends ton temps. Rien ici ne s'en va. Nous non plus.",
      "Chaque éclat que tu m'apportes retourne au ciel. Lève les yeux, une nuit.",
      "Tu as l'air à court. Comme presque tout le monde.",
      "Reviens. Tu reviendras. Tout le monde revient."
    ]
  }
};
