"""Generates the web versions of the brand assets: the logo (WebP, and PNG for e-mails)
and the favicon set.

Usage: python assets-src/optimize.py (npm run assets)
Everything else in the world is pixel art generated by code (apps/web/src/game/pixel);
its static export, the OpenGraph image, comes from `npm run art`.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "original"
OUT = ROOT.parent / "apps" / "web" / "public" / "assets"

# (folder, max size of the longest side, quality)
RULES = {
    "brand": (900, 92),
}

def trim(image: Image.Image) -> Image.Image:
    if image.mode != "RGBA":
        return image
    bbox = image.getchannel("A").point(lambda a: 255 if a > 8 else 0).getbbox()
    return image.crop(bbox) if bbox else image

for folder, (size, quality) in RULES.items():
    for source in sorted((SRC / folder).glob("*.png")):
        image = Image.open(source)
        image = trim(image.convert("RGBA")) if image.mode == "RGBA" else image.convert("RGB")
        image.thumbnail((size, size), Image.LANCZOS)
        target = OUT / folder / (source.stem.replace("-transparent", "") + ".webp")
        target.parent.mkdir(parents=True, exist_ok=True)
        image.save(target, "WEBP", quality=quality, method=6)
        print(f"{target.relative_to(OUT)}  {image.size}  {target.stat().st_size // 1024} KB")

icon = Image.open(ROOT / "favicon.png").convert("RGBA")
for s in (32, 180, 512):
    copy = icon.copy(); copy.thumbnail((s, s), Image.LANCZOS)
    copy.save(OUT.parent / ("favicon.png" if s == 32 else f"icon-{s}.png"))

# E-mail logo: PNG, since several mail clients do not display WebP. Shown at 220px, 2x.
mail_logo = trim(Image.open(SRC / "brand" / "idlebound-logo.png").convert("RGBA"))
mail_logo.thumbnail((440, 440), Image.LANCZOS)
# 256-color palette: a quarter of the size, no visible difference at this scale.
mail_logo.quantize(256, method=Image.FASTOCTREE, dither=Image.FLOYDSTEINBERG).save(OUT / "brand" / "idlebound-logo-mail.png", optimize=True)
print("brand/idlebound-logo-mail.png generated")
